JSON_(ERROR_(CTRL_CHAR|DEPTH|INF_OR_NAN|INVALID_PROPERTY_NAME|NON_BACKED_ENUM|NONE|RECURSION
            |STATE_MISMATCH|SYNTAX|UNSUPPORTED_TYPE|UTF(16|8))
     |BIGINT_AS_STRING|FORCE_OBJECT|HEX_(AMP|APOS|QUOT|TAG)|INVALID_UTF8_(IGNORE|SUBSTITUTE)
     |NUMERIC_CHECK|OBJECT_AS_ARRAY|(PARTIAL_OUTPUT|THROW)_ON_ERROR|PRESERVE_ZERO_FRACTION
     |PRETTY_PRINT|UNESCAPED_(LINE_TERMINATORS|SLASHES|UNICODE))
