CAL_(FRENCH|DOW_(DAYNO|LONG|SHORT)|EASTER_(ALWAYS_(GREGORIAN|JULIAN)|DEFAULT|ROMAN)
    |GREGORIAN|JEWISH(_ADD_(ALAFIM|ALAFIM_GERESH|GERESHAYIM))?|JULIAN
    |MONTH_(FRENCH|JEWISH|GREGORIAN_(LONG|SHORT)|JULIAN_(LONG|SHORT))|NUM_CALS)
