LIBXML_(BIGLINES|XINCLUDE|NSCLEAN|NO(XMLDECL|BLANKS|NET|CDATA|ERROR|EMPTYTAG|ENT|WARNING)
        |COMPACT|DTD(VALID|LOAD|ATTR)|((DOTTED|LOADED)_)?VERSION|PARSEHUGE|PEDANTIC|RECOVER
        |SCHEMA_CREATE|ERR_(NONE|ERROR|FATAL|WARNING)|HTML_(NO(DEFDTD|IMPLIED)))