XML_(SAX_IMPL|OPTION_(SKIP_(TAGSTART|WHITE)|CASE_FOLDING|PARSE_HUGE|TARGET_ENCODING)
    |ERROR_((BAD_CHAR|(ATTRIBUTE_EXTERNAL|BINARY|PARAM|RECURSIVE)_ENTITY)_REF|MISPLACED_XML_PI|SYNTAX|NONE
           |NO_(MEMORY|ELEMENTS)|TAG_MISMATCH|INCORRECT_ENCODING|INVALID_TOKEN|DUPLICATE_ATTRIBUTE
           |UNCLOSED_(CDATA_SECTION|TOKEN)|UNDEFINED_ENTITY|UNKNOWN_ENCODING|JUNK_AFTER_DOC_ELEMENT
           |PARTIAL_CHAR|EXTERNAL_ENTITY_HANDLING|ASYNC_ENTITY))