(DOMSTRING_SIZE_ERR
|DOM_((SYNTAX|HIERARCHY_REQUEST|NO_(MODIFICATION_ALLOWED|DATA_ALLOWED)|NOT_(FOUND|SUPPORTED)|NAMESPACE
|INDEX_SIZE|INUSE_ATTRIBUTE|INVALID_(ACCESS|CHARACTER|MODIFICATION|STATE)|PHP|VALIDATION|WRONG_DOCUMENT)_ERR)
|XML_((DTD|DOCUMENT(_(FRAG|TYPE))?|HTML_DOCUMENT|NOTATION|NAMESPACE_DECL|PI|COMMENT|DATA_SECTION|TEXT)_NODE
      |ENTITY_(((REF|DECL)_)?NODE)|ELEMENT(_DECL)?_NODE|LOCAL_NAMESPACE
      |ATTRIBUTE_(NMTOKEN(S)?|NOTATION|NODE|CDATA|DECL_NODE|ENTITY|ENUMERATION|ID(REF(S)?)?)
      |CDATA_SECTION_NODE|ID(REF(S)?)?|DECL_NODE|ENTITY|ENUMERATION))