<?php

//added
CURLALTSVC_H1;
CURLALTSVC_H2;
CURLALTSVC_H3;
CURLALTSVC_READONLYFILE;

// re-added
CURLAUTH_ANY;
CURLAUTH_ANYSAFE;
CURLAUTH_AWS_SIGV4;
CURLAUTH_BASIC;
CURLAUTH_BEARER;
CURLAUTH_DIGEST;
CURLAUTH_DIGEST_IE;
CURLAUTH_GSSAPI;
CURLAUTH_GSSNEGOTIATE;
CURLAUTH_NEGOTIATE;
CURLAUTH_NONE;
CURLAUTH_NTLM;
CURLAUTH_NTLM_WB;
CURLAUTH_ONLY;

CURLM_ADDED_ALREADY;    //added
CURLM_BAD_EASY_HANDLE;  // fixed
CURLM_BAD_HANDLE;
CURLM_CALL_MULTI_PERFORM;
CURLM_INTERNAL_ERROR;
CURLM_OK;
CURLM_OUT_OF_MEMORY;

CURLMSG_DONE;

CURLSSH_AUTH_AGENT;
CURLSSH_AUTH_ANY;
CURLSSH_AUTH_DEFAULT;
CURLSSH_AUTH_GSSAPI;
CURLSSH_AUTH_HOST;
CURLSSH_AUTH_KEYBOARD;
CURLSSH_AUTH_NONE;
CURLSSH_AUTH_PASSWORD;
CURLSSH_AUTH_PUBLICKEY;


// REMOVED FROM PHP:
CURLCLOSEPOLICY_CALLBACK;
CURLCLOSEPOLICY_LEAST_RECENTLY_USED;
CURLCLOSEPOLICY_LEAST_TRAFFIC;
CURLCLOSEPOLICY_OLDEST;
CURLCLOSEPOLICY_SLOWEST;


CURLE_ABORTED_BY_CALLBACK;
CURLE_BAD_CALLING_ORDER;
CURLE_BAD_CONTENT_ENCODING;
CURLE_BAD_DOWNLOAD_RESUME;
CURLE_BAD_FUNCTION_ARGUMENT;
CURLE_BAD_PASSWORD_ENTERED;
CURLE_COULDNT_CONNECT;
CURLE_COULDNT_RESOLVE_HOST;
CURLE_COULDNT_RESOLVE_PROXY;
CURLE_FAILED_INIT;
CURLE_FILESIZE_EXCEEDED;
CURLE_FILE_COULDNT_READ_FILE;

CURLE_FTP_ACCESS_DENIED;
CURLE_FTP_BAD_DOWNLOAD_RESUME;
CURLE_FTP_CANT_GET_HOST;
CURLE_FTP_CANT_RECONNECT;
CURLE_FTP_COULDNT_GET_SIZE;
CURLE_FTP_COULDNT_RETR_FILE;
CURLE_FTP_COULDNT_SET_ASCII;
CURLE_FTP_COULDNT_SET_BINARY;
CURLE_FTP_COULDNT_STOR_FILE;
CURLE_FTP_COULDNT_USE_REST;
CURLE_FTP_PARTIAL_FILE;
CURLE_FTP_PORT_FAILED;
CURLE_FTP_QUOTE_ERROR;
CURLE_FTP_SSL_FAILED;
CURLE_FTP_USER_PASSWORD_INCORRECT;
CURLE_FTP_WEIRD_227_FORMAT;
CURLE_FTP_WEIRD_PASS_REPLY;
CURLE_FTP_WEIRD_PASV_REPLY;
CURLE_FTP_WEIRD_SERVER_REPLY;
CURLE_FTP_WEIRD_USER_REPLY;
CURLE_FTP_WRITE_ERROR;

CURLE_FUNCTION_NOT_FOUND;
CURLE_GOT_NOTHING;
CURLE_HTTP_NOT_FOUND;
CURLE_HTTP_PORT_FAILED;
CURLE_HTTP_POST_ERROR;
CURLE_HTTP_RANGE_ERROR;
CURLE_HTTP_RETURNED_ERROR;
CURLE_LDAP_CANNOT_BIND;
CURLE_LDAP_INVALID_URL;
CURLE_LDAP_SEARCH_FAILED;
CURLE_LIBRARY_NOT_FOUND;
CURLE_MALFORMAT_USER;
CURLE_OBSOLETE;
CURLE_OK;
CURLE_OPERATION_TIMEDOUT;
CURLE_OPERATION_TIMEOUTED;
CURLE_OUT_OF_MEMORY;
CURLE_PARTIAL_FILE;
CURLE_PROXY;
CURLE_READ_ERROR;
CURLE_RECV_ERROR;
CURLE_SEND_ERROR;
CURLE_SHARE_IN_USE;
CURLE_SSH;
CURLE_SSL_CACERT;
CURLE_SSL_CACERT_BADFILE;
CURLE_SSL_CERTPROBLEM;
CURLE_SSL_CIPHER;
CURLE_SSL_CONNECT_ERROR;
CURLE_SSL_ENGINE_NOTFOUND;
CURLE_SSL_ENGINE_SETFAILED;
CURLE_SSL_PEER_CERTIFICATE;
CURLE_SSL_PINNEDPUBKEYNOTMATCH;
CURLE_TELNET_OPTION_SYNTAX;
CURLE_TOO_MANY_REDIRECTS;
CURLE_UNKNOWN_TELNET_OPTION;
CURLE_UNSUPPORTED_PROTOCOL;
CURLE_URL_MALFORMAT;
CURLE_URL_MALFORMAT_USER;
CURLE_WEIRD_SERVER_REPLY;
CURLE_WRITE_ERROR;

CURLFTPAUTH_DEFAULT;
CURLFTPAUTH_SSL;
CURLFTPAUTH_TLS;
CURLFTPMETHOD_DEFAULT;
CURLFTPMETHOD_MULTICWD;
CURLFTPMETHOD_NOCWD;
CURLFTPMETHOD_SINGLECWD;
CURLFTPSSL_ALL;
CURLFTPSSL_CCC_ACTIVE;
CURLFTPSSL_CCC_NONE;
CURLFTPSSL_CCC_PASSIVE;
CURLFTPSSL_CONTROL;
CURLFTPSSL_NONE;
CURLFTPSSL_TRY;
CURLFTP_CREATE_DIR;
CURLFTP_CREATE_DIR_NONE;
CURLFTP_CREATE_DIR_RETRY;

CURLGSSAPI_DELEGATION_FLAG;
CURLGSSAPI_DELEGATION_POLICY_FLAG;

CURLHEADER_SEPARATE;
CURLHEADER_UNIFIED;
CURLHSTS_ENABLE;
CURLHSTS_READONLYFILE;

CURLINFO_APPCONNECT_TIME;
CURLINFO_APPCONNECT_TIME_T;
CURLINFO_CAINFO;
CURLINFO_CAPATH;
CURLINFO_CERTINFO; // fixed
CURLINFO_CONDITION_UNMET;
CURLINFO_CONNECT_TIME; // fixed
CURLINFO_CONNECT_TIME_T;
CURLINFO_CONTENT_LENGTH_DOWNLOAD; // fixed
CURLINFO_CONTENT_LENGTH_DOWNLOAD_T;
CURLINFO_CONTENT_LENGTH_UPLOAD; // fixed
CURLINFO_CONTENT_LENGTH_UPLOAD_T;
CURLINFO_CONTENT_TYPE; // fixed
CURLINFO_COOKIELIST;
CURLINFO_DATA_IN;
CURLINFO_DATA_OUT;
CURLINFO_EFFECTIVE_METHOD;
CURLINFO_EFFECTIVE_URL; // fixed
CURLINFO_FILETIME; // fixed
CURLINFO_FILETIME_T;
CURLINFO_FTP_ENTRY_PATH;
CURLINFO_HEADER_IN;
CURLINFO_HEADER_OUT; // fixed
CURLINFO_HEADER_SIZE; // fixed
CURLINFO_HTTPAUTH_AVAIL;
CURLINFO_HTTP_CODE; // fixed
CURLINFO_HTTP_CONNECTCODE;
CURLINFO_HTTP_VERSION;
CURLINFO_LASTONE;
CURLINFO_LOCAL_IP;
CURLINFO_LOCAL_PORT;
CURLINFO_NAMELOOKUP_TIME; // fixed
CURLINFO_NAMELOOKUP_TIME_T;
CURLINFO_NUM_CONNECTS;
CURLINFO_OS_ERRNO;
CURLINFO_POSTTRANSFER_TIME_T;
CURLINFO_PRETRANSFER_TIME; // fixed
CURLINFO_PRETRANSFER_TIME_T;
CURLINFO_PRIMARY_IP;
CURLINFO_PRIMARY_PORT;
CURLINFO_PRIVATE; // fixed
CURLINFO_PROTOCOL;
CURLINFO_PROXYAUTH_AVAIL;
CURLINFO_PROXY_ERROR;
CURLINFO_PROXY_SSL_VERIFYRESULT;
CURLINFO_REDIRECT_COUNT; // fixed
CURLINFO_REDIRECT_TIME; // fixed
CURLINFO_REDIRECT_TIME_T;
CURLINFO_REDIRECT_URL;
CURLINFO_REFERER;
CURLINFO_REQUEST_SIZE; // fixed
CURLINFO_RESPONSE_CODE;
CURLINFO_RETRY_AFTER;
CURLINFO_RTSP_CLIENT_CSEQ;
CURLINFO_RTSP_CSEQ_RECV;
CURLINFO_RTSP_SERVER_CSEQ;
CURLINFO_RTSP_SESSION_ID;
CURLINFO_SCHEME;
CURLINFO_SIZE_DOWNLOAD;
CURLINFO_SIZE_DOWNLOAD_T;
CURLINFO_SIZE_UPLOAD;
CURLINFO_SIZE_UPLOAD_T;
CURLINFO_SPEED_DOWNLOAD;
CURLINFO_SPEED_DOWNLOAD_T;
CURLINFO_SPEED_UPLOAD;
CURLINFO_SPEED_UPLOAD_T;
CURLINFO_SSL_DATA_IN;
CURLINFO_SSL_DATA_OUT;
CURLINFO_SSL_ENGINES;
CURLINFO_SSL_VERIFYRESULT; // fixed
CURLINFO_STARTTRANSFER_TIME;
CURLINFO_STARTTRANSFER_TIME_T;
CURLINFO_TEXT;
CURLINFO_TOTAL_TIME; // fixed
CURLINFO_TOTAL_TIME_T;

CURLKHMATCH_LAST;
CURLKHMATCH_MISMATCH;
CURLKHMATCH_MISSING;
CURLKHMATCH_OK;

CURLMIMEOPT_FORMESCAPE;

CURLMOPT_CHUNK_LENGTH_PENALTY_SIZE;
CURLMOPT_CONTENT_LENGTH_PENALTY_SIZE;
CURLMOPT_MAXCONNECTS;
CURLMOPT_MAX_CONCURRENT_STREAMS;
CURLMOPT_MAX_HOST_CONNECTIONS;
CURLMOPT_MAX_PIPELINE_LENGTH;
CURLMOPT_MAX_TOTAL_CONNECTIONS;
CURLMOPT_PIPELINING;
CURLMOPT_PUSHFUNCTION;

CURLOPT_ABSTRACT_UNIX_SOCKET;
CURLOPT_ACCEPTTIMEOUT_MS;
CURLOPT_ACCEPT_ENCODING;
CURLOPT_ADDRESS_SCOPE;
CURLOPT_ALTSVC;
CURLOPT_ALTSVC_CTRL;
CURLOPT_APPEND;
CURLOPT_AUTOREFERER; // fixed
CURLOPT_AWS_SIGV4;
CURLOPT_BINARYTRANSFER; // fixed
CURLOPT_BUFFERSIZE; // fixed
CURLOPT_CAINFO; // fixed
CURLOPT_CAINFO_BLOB;
CURLOPT_CAPATH; // fixed
CURLOPT_CA_CACHE_TIMEOUT;
CURLOPT_CERTINFO; // fixed
CURLOPT_CLOSEPOLICY; // fixed // REMOVED FROM PHP
CURLOPT_CONNECTTIMEOUT; // fixed
CURLOPT_CONNECTTIMEOUT_MS; // fixed
CURLOPT_CONNECT_ONLY;
CURLOPT_CONNECT_TO;
CURLOPT_COOKIE; // fixed
CURLOPT_COOKIEFILE; // fixed
CURLOPT_COOKIEJAR; // fixed
CURLOPT_COOKIELIST;
CURLOPT_COOKIESESSION; // fixed
CURLOPT_CRLF; // fixed
CURLOPT_CRLFILE;
CURLOPT_CUSTOMREQUEST; // fixed
CURLOPT_DEBUGFUNCTION;
CURLOPT_DEFAULT_PROTOCOL;
CURLOPT_DIRLISTONLY;
CURLOPT_DISALLOW_USERNAME_IN_URL;
CURLOPT_DNS_CACHE_TIMEOUT; // fixed
CURLOPT_DNS_INTERFACE;
CURLOPT_DNS_LOCAL_IP4;
CURLOPT_DNS_LOCAL_IP6;
CURLOPT_DNS_SERVERS;
CURLOPT_DNS_SHUFFLE_ADDRESSES;
CURLOPT_DNS_USE_GLOBAL_CACHE; // fixed
CURLOPT_DOH_SSL_VERIFYHOST;
CURLOPT_DOH_SSL_VERIFYPEER;
CURLOPT_DOH_SSL_VERIFYSTATUS;
CURLOPT_DOH_URL;
CURLOPT_EGDSOCKET; // fixed
CURLOPT_ENCODING; // fixed
CURLOPT_EXPECT_100_TIMEOUT_MS;
CURLOPT_FAILONERROR; // fixed
CURLOPT_FILE; // fixed
CURLOPT_FILETIME; // fixed
CURLOPT_FNMATCH_FUNCTION;
CURLOPT_FOLLOWLOCATION; // fixed
CURLOPT_FORBID_REUSE; // fixed
CURLOPT_FRESH_CONNECT; // fixed
CURLOPT_FTPAPPEND; // fixed
CURLOPT_FTPLISTONLY; // fixed
CURLOPT_FTPPORT; // fixed
CURLOPT_FTPSSLAUTH; // fixed
CURLOPT_FTP_ACCOUNT;
CURLOPT_FTP_ALTERNATIVE_TO_USER;
CURLOPT_FTP_CREATE_MISSING_DIRS; // fixed
CURLOPT_FTP_FILEMETHOD; // fixed
CURLOPT_FTP_RESPONSE_TIMEOUT;
CURLOPT_FTP_SKIP_PASV_IP; // fixed
CURLOPT_FTP_SSL; // fixed
CURLOPT_FTP_SSL_CCC;
CURLOPT_FTP_USE_EPRT; // fixed
CURLOPT_FTP_USE_EPSV; // fixed
CURLOPT_FTP_USE_PRET;
CURLOPT_GSSAPI_DELEGATION;
CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS;
CURLOPT_HAPROXYPROTOCOL;
CURLOPT_HEADER; // fixed
CURLOPT_HEADERFUNCTION; // fixed
CURLOPT_HEADEROPT;
CURLOPT_HSTS;
CURLOPT_HSTS_CTRL;
CURLOPT_HTTP09_ALLOWED;
CURLOPT_HTTP200ALIASES; // fixed
CURLOPT_HTTPAUTH; // fixed
CURLOPT_HTTPGET; // fixed
CURLOPT_HTTPHEADER; // fixed
CURLOPT_HTTPPROXYTUNNEL; // fixed
CURLOPT_HTTP_CONTENT_DECODING;
CURLOPT_HTTP_TRANSFER_DECODING;
CURLOPT_HTTP_VERSION; // fixed
CURLOPT_IGNORE_CONTENT_LENGTH;
CURLOPT_INFILE; // fixed
CURLOPT_INFILESIZE; // fixed
CURLOPT_INTERFACE; // fixed
CURLOPT_IPRESOLVE; // fixed
CURLOPT_ISSUERCERT;
CURLOPT_ISSUERCERT_BLOB;
CURLOPT_KEEP_SENDING_ON_ERROR;
CURLOPT_KEYPASSWD; // fixed
CURLOPT_KRB4LEVEL; // fixed
CURLOPT_KRBLEVEL;
CURLOPT_LOCALPORT;
CURLOPT_LOCALPORTRANGE;
CURLOPT_LOGIN_OPTIONS;
CURLOPT_LOW_SPEED_LIMIT; // fixed
CURLOPT_LOW_SPEED_TIME; // fixed
CURLOPT_MAIL_AUTH;
CURLOPT_MAIL_FROM;
CURLOPT_MAIL_RCPT;
CURLOPT_MAIL_RCPT_ALLLOWFAILS;
CURLOPT_MAXAGE_CONN;
CURLOPT_MAXCONNECTS; // fixed
CURLOPT_MAXFILESIZE;
CURLOPT_MAXFILESIZE_LARGE;
CURLOPT_MAXLIFETIME_CONN;
CURLOPT_MAXREDIRS; // fixed
CURLOPT_MAX_RECV_SPEED_LARGE;
CURLOPT_MAX_SEND_SPEED_LARGE;
CURLOPT_MIME_OPTIONS;
CURLOPT_NETRC; // fixed
CURLOPT_NETRC_FILE;
CURLOPT_NEW_DIRECTORY_PERMS;
CURLOPT_NEW_FILE_PERMS;
CURLOPT_NOBODY; // fixed
CURLOPT_NOPROGRESS; // fixed
CURLOPT_NOPROXY;
CURLOPT_NOSIGNAL; // fixed
CURLOPT_PASSWORD;
CURLOPT_PATH_AS_IS;
CURLOPT_PINNEDPUBLICKEY;
CURLOPT_PIPEWAIT;
CURLOPT_PORT; // fixed
CURLOPT_POST; // fixed
CURLOPT_POSTFIELDS; // fixed
CURLOPT_POSTQUOTE; // fixed
CURLOPT_POSTREDIR; // fixed
CURLOPT_PREQUOTE;
CURLOPT_PREREQFUNCTION;
CURLOPT_PRE_PROXY;
CURLOPT_PRIVATE; // fixed
CURLOPT_PROGRESSFUNCTION; // fixed
CURLOPT_PROTOCOLS; // fixed
CURLOPT_PROTOCOLS_STR;
CURLOPT_PROXY; // fixed
CURLOPT_PROXYAUTH; // fixed
CURLOPT_PROXYHEADER;
CURLOPT_PROXYPASSWORD;
CURLOPT_PROXYPORT; // fixed
CURLOPT_PROXYTYPE; // fixed
CURLOPT_PROXYUSERNAME;
CURLOPT_PROXYUSERPWD; // fixed
CURLOPT_PROXY_CAINFO;
CURLOPT_PROXY_CAINFO_BLOB;
CURLOPT_PROXY_CAPATH;
CURLOPT_PROXY_CRLFILE;
CURLOPT_PROXY_ISSUERCERT;
CURLOPT_PROXY_ISSUERCERT_BLOB;
CURLOPT_PROXY_KEYPASSWD;
CURLOPT_PROXY_PINNEDPUBLICKEY;
CURLOPT_PROXY_SERVICE_NAME;
CURLOPT_PROXY_SSLCERT;
CURLOPT_PROXY_SSLCERTTYPE;
CURLOPT_PROXY_SSLCERT_BLOB;
CURLOPT_PROXY_SSLKEY;
CURLOPT_PROXY_SSLKEYTYPE;
CURLOPT_PROXY_SSLKEY_BLOB;
CURLOPT_PROXY_SSLVERSION;
CURLOPT_PROXY_SSL_CIPHER_LIST;
CURLOPT_PROXY_SSL_OPTIONS;
CURLOPT_PROXY_SSL_VERIFYHOST;
CURLOPT_PROXY_SSL_VERIFYPEER;
CURLOPT_PROXY_TLS13_CIPHERS;
CURLOPT_PROXY_TLSAUTH_PASSWORD;
CURLOPT_PROXY_TLSAUTH_TYPE;
CURLOPT_PROXY_TLSAUTH_USERNAME;
CURLOPT_PROXY_TRANSFER_MODE;
CURLOPT_PUT; // fixed
CURLOPT_QUICK_EXIT;
CURLOPT_QUOTE; // fixed
CURLOPT_RANDOM_FILE; // fixed
CURLOPT_RANGE; // fixed
CURLOPT_READDATA; // fixed
CURLOPT_READFUNCTION; // fixed
CURLOPT_REDIR_PROTOCOLS; // fixed
CURLOPT_REDIR_PROTOCOLS_STR;
CURLOPT_REFERER; // fixed
CURLOPT_REQUEST_TARGET;
CURLOPT_RESOLVE;
CURLOPT_RESUME_FROM; // fixed
CURLOPT_RETURNTRANSFER; // fixed
CURLOPT_RTSP_CLIENT_CSEQ;
CURLOPT_RTSP_REQUEST;
CURLOPT_RTSP_SERVER_CSEQ;
CURLOPT_RTSP_SESSION_ID;
CURLOPT_RTSP_STREAM_URI;
CURLOPT_RTSP_TRANSPORT;
CURLOPT_SAFE_UPLOAD;
CURLOPT_SASL_AUTHZID;
CURLOPT_SASL_IR;
CURLOPT_SERVER_RESPONSE_TIMEOUT;
CURLOPT_SERVICE_NAME;
CURLOPT_SHARE;
CURLOPT_SOCKS5_AUTH;
CURLOPT_SOCKS5_GSSAPI_NEC;
CURLOPT_SOCKS5_GSSAPI_SERVICE;

CURLOPT_SSH_AUTH_TYPES; // fixed
CURLOPT_SSH_COMPRESSION;
CURLOPT_SSH_HOSTKEYFUNCTION;
CURLOPT_SSH_HOST_PUBLIC_KEY_MD5; // fixed
CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256;
CURLOPT_SSH_KNOWNHOSTS;
CURLOPT_SSH_PRIVATE_KEYFILE; // fixed
CURLOPT_SSH_PUBLIC_KEYFILE; // fixed

CURLOPT_SSLCERT; // fixed
CURLOPT_SSLCERTPASSWD; // fixed
CURLOPT_SSLCERTTYPE; // fixed
CURLOPT_SSLCERT_BLOB;
CURLOPT_SSLENGINE; // fixed
CURLOPT_SSLENGINE_DEFAULT; // fixed
CURLOPT_SSLKEY; // fixed
CURLOPT_SSLKEYPASSWD; // fixed
CURLOPT_SSLKEYTYPE; // fixed
CURLOPT_SSLKEY_BLOB;
CURLOPT_SSLVERSION; // fixed

CURLOPT_SSL_CIPHER_LIST; // fixed
CURLOPT_SSL_EC_CURVES;
CURLOPT_SSL_ENABLE_ALPN;
CURLOPT_SSL_ENABLE_NPN;
CURLOPT_SSL_FALSESTART;
CURLOPT_SSL_OPTIONS;
CURLOPT_SSL_SESSIONID_CACHE;
CURLOPT_SSL_VERIFYHOST; // fixed
CURLOPT_SSL_VERIFYPEER; // fixed
CURLOPT_SSL_VERIFYSTATUS;

CURLOPT_STDERR; // fixed
CURLOPT_STREAM_WEIGHT;
CURLOPT_SUPPRESS_CONNECT_HEADERS;
CURLOPT_TCP_FASTOPEN;
CURLOPT_TCP_KEEPALIVE;
CURLOPT_TCP_KEEPCNT;
CURLOPT_TCP_KEEPIDLE;
CURLOPT_TCP_KEEPINTVL;
CURLOPT_TCP_NODELAY; // fixed
CURLOPT_TELNETOPTIONS;
CURLOPT_TFTP_BLKSIZE;
CURLOPT_TFTP_NO_OPTIONS;
CURLOPT_TIMECONDITION; // fixed
CURLOPT_TIMEOUT; // fixed
CURLOPT_TIMEOUT_MS; // fixed
CURLOPT_TIMEVALUE; // fixed
CURLOPT_TIMEVALUE_LARGE;
CURLOPT_TLS13_CIPHERS;
CURLOPT_TLSAUTH_PASSWORD;
CURLOPT_TLSAUTH_TYPE;
CURLOPT_TLSAUTH_USERNAME;
CURLOPT_TRANSFERTEXT; // fixed
CURLOPT_TRANSFER_ENCODING;
CURLOPT_UNIX_SOCKET_PATH;
CURLOPT_UNRESTRICTED_AUTH; // fixed
CURLOPT_UPKEEP_INTERVAL_MS;
CURLOPT_UPLOAD; // fixed
CURLOPT_UPLOAD_BUFFERSIZE;
CURLOPT_URL; // fixed
CURLOPT_USERAGENT; // fixed
CURLOPT_USERNAME;
CURLOPT_USERPWD; // fixed
CURLOPT_USE_SSL;
CURLOPT_VERBOSE; // fixed
CURLOPT_WILDCARDMATCH;
CURLOPT_WRITEFUNCTION; // fixed
CURLOPT_WRITEHEADER; // fixed
CURLOPT_WS_OPTIONS;
CURLOPT_XFERINFOFUNCTION;
CURLOPT_XOAUTH2_BEARER;

CURLPAUSE_ALL;
CURLPAUSE_CONT;
CURLPAUSE_RECV;
CURLPAUSE_RECV_CONT;
CURLPAUSE_SEND;
CURLPAUSE_SEND_CONT;

CURLPIPE_HTTP1;
CURLPIPE_MULTIPLEX;
CURLPIPE_NOTHING;

CURLPROTO_ALL;
CURLPROTO_DICT;
CURLPROTO_FILE;
CURLPROTO_FTP;
CURLPROTO_FTPS;
CURLPROTO_GOPHER;
CURLPROTO_HTTP;
CURLPROTO_HTTPS;
CURLPROTO_IMAP;
CURLPROTO_IMAPS;
CURLPROTO_LDAP;
CURLPROTO_LDAPS;
CURLPROTO_MQTT;
CURLPROTO_POP3;
CURLPROTO_POP3S;
CURLPROTO_RTMP;
CURLPROTO_RTMPE;
CURLPROTO_RTMPS;
CURLPROTO_RTMPT;
CURLPROTO_RTMPTE;
CURLPROTO_RTMPTS;
CURLPROTO_RTSP;
CURLPROTO_SCP;
CURLPROTO_SFTP;
CURLPROTO_SMB;
CURLPROTO_SMBS;
CURLPROTO_SMTP;
CURLPROTO_SMTPS;
CURLPROTO_TELNET;
CURLPROTO_TFTP;

CURLPROXY_HTTP;
CURLPROXY_HTTPS;
CURLPROXY_HTTP_1_0;
CURLPROXY_SOCKS4;
CURLPROXY_SOCKS4A;
CURLPROXY_SOCKS5;
CURLPROXY_SOCKS5_HOSTNAME;

CURLPX_BAD_ADDRESS_TYPE;
CURLPX_BAD_VERSION;
CURLPX_CLOSED;
CURLPX_GSSAPI;
CURLPX_GSSAPI_PERMSG;
CURLPX_GSSAPI_PROTECTION;
CURLPX_IDENTD;
CURLPX_IDENTD_DIFFER;
CURLPX_LONG_HOSTNAME;
CURLPX_LONG_PASSWD;
CURLPX_LONG_USER;
CURLPX_NO_AUTH;
CURLPX_OK;
CURLPX_RECV_ADDRESS;
CURLPX_RECV_AUTH;
CURLPX_RECV_CONNECT;
CURLPX_RECV_REQACK;
CURLPX_REPLY_ADDRESS_TYPE_NOT_SUPPORTED;
CURLPX_REPLY_COMMAND_NOT_SUPPORTED;
CURLPX_REPLY_CONNECTION_REFUSED;
CURLPX_REPLY_GENERAL_SERVER_FAILURE;
CURLPX_REPLY_HOST_UNREACHABLE;
CURLPX_REPLY_NETWORK_UNREACHABLE;
CURLPX_REPLY_NOT_ALLOWED;
CURLPX_REPLY_TTL_EXPIRED;
CURLPX_REPLY_UNASSIGNED;
CURLPX_REQUEST_FAILED;
CURLPX_RESOLVE_HOST;
CURLPX_SEND_AUTH;
CURLPX_SEND_CONNECT;
CURLPX_SEND_REQUEST;
CURLPX_UNKNOWN_FAIL;
CURLPX_UNKNOWN_MODE;
CURLPX_USER_REJECTED;
CURLSHOPT_NONE;
CURLSHOPT_SHARE;
CURLSHOPT_UNSHARE;


CURLSSLOPT_ALLOW_BEAST;
CURLSSLOPT_AUTO_CLIENT_CERT;
CURLSSLOPT_NATIVE_CA;
CURLSSLOPT_NO_PARTIALCHAIN;
CURLSSLOPT_NO_REVOKE;
CURLSSLOPT_REVOKE_BEST_EFFORT;
CURLUSESSL_ALL;
CURLUSESSL_CONTROL;
CURLUSESSL_NONE;
CURLUSESSL_TRY;

CURLVERSION_NOW;

CURLWS_RAW_MODE;
CURL_FNMATCHFUNC_FAIL;
CURL_FNMATCHFUNC_MATCH;
CURL_FNMATCHFUNC_NOMATCH;

CURL_HTTP_VERSION_1_0;
CURL_HTTP_VERSION_1_1;
CURL_HTTP_VERSION_2;
CURL_HTTP_VERSION_2TLS;
CURL_HTTP_VERSION_2_0;
CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE;
CURL_HTTP_VERSION_3;
CURL_HTTP_VERSION_3ONLY;
CURL_HTTP_VERSION_NONE;

CURL_IPRESOLVE_V4;
CURL_IPRESOLVE_V6;
CURL_IPRESOLVE_WHATEVER;

CURL_LOCK_DATA_CONNECT;
CURL_LOCK_DATA_COOKIE;
CURL_LOCK_DATA_DNS;
CURL_LOCK_DATA_PSL;
CURL_LOCK_DATA_SSL_SESSION;
CURL_MAX_READ_SIZE;

CURL_NETRC_IGNORED;
CURL_NETRC_OPTIONAL;
CURL_NETRC_REQUIRED;

CURL_PREREQFUNC_ABORT;
CURL_PREREQFUNC_OK;
CURL_PUSH_DENY;
CURL_PUSH_OK;
CURL_READFUNC_PAUSE;
CURL_REDIR_POST_301;
CURL_REDIR_POST_302;
CURL_REDIR_POST_303;
CURL_REDIR_POST_ALL;
CURL_RTSPREQ_ANNOUNCE;
CURL_RTSPREQ_DESCRIBE;
CURL_RTSPREQ_GET_PARAMETER;
CURL_RTSPREQ_OPTIONS;
CURL_RTSPREQ_PAUSE;
CURL_RTSPREQ_PLAY;
CURL_RTSPREQ_RECEIVE;
CURL_RTSPREQ_RECORD;
CURL_RTSPREQ_SETUP;
CURL_RTSPREQ_SET_PARAMETER;
CURL_RTSPREQ_TEARDOWN;
CURL_SSLVERSION_DEFAULT;
CURL_SSLVERSION_MAX_DEFAULT;
CURL_SSLVERSION_MAX_NONE;
CURL_SSLVERSION_MAX_TLSv1_0;
CURL_SSLVERSION_MAX_TLSv1_1;
CURL_SSLVERSION_MAX_TLSv1_2;
CURL_SSLVERSION_MAX_TLSv1_3;
CURL_SSLVERSION_SSLv2;
CURL_SSLVERSION_SSLv3;
CURL_SSLVERSION_TLSv1;
CURL_SSLVERSION_TLSv1_0;
CURL_SSLVERSION_TLSv1_1;
CURL_SSLVERSION_TLSv1_2;
CURL_SSLVERSION_TLSv1_3;

CURL_TIMECOND_IFMODSINCE;
CURL_TIMECOND_IFUNMODSINCE;
CURL_TIMECOND_LASTMOD;
CURL_TIMECOND_NONE;

CURL_TLSAUTH_SRP;

CURL_VERSION_ALTSVC;
CURL_VERSION_ASYNCHDNS;
CURL_VERSION_BROTLI;
CURL_VERSION_CONV;
CURL_VERSION_CURLDEBUG;
CURL_VERSION_DEBUG;
CURL_VERSION_GSASL;
CURL_VERSION_GSSAPI;
CURL_VERSION_GSSNEGOTIATE;
CURL_VERSION_HSTS;
CURL_VERSION_HTTP2;
CURL_VERSION_HTTP3;
CURL_VERSION_HTTPS_PROXY;
CURL_VERSION_IDN;
CURL_VERSION_IPV6;
CURL_VERSION_KERBEROS4;
CURL_VERSION_KERBEROS5;
CURL_VERSION_LARGEFILE;
CURL_VERSION_LIBZ;
CURL_VERSION_MULTI_SSL;
CURL_VERSION_NTLM;
CURL_VERSION_NTLM_WB;
CURL_VERSION_PSL;
CURL_VERSION_SPNEGO;
CURL_VERSION_SSL;
CURL_VERSION_SSPI;
CURL_VERSION_TLSAUTH_SRP;
CURL_VERSION_UNICODE;
CURL_VERSION_UNIX_SOCKETS;
CURL_VERSION_ZSTD;
CURL_WRITEFUNC_PAUSE;