#!/bin/bash

pnpm run -s regex-builder for-grammar/input/ext.intl.txt --no-split=VALID,STANDARD,TOKEN,VERSION,OPTION,FILTER,PROHIBITED,ACCESS,RULE,OPERATOR > for-grammar/ext.intl.re

pnpm run -s regex-builder for-grammar/input/ext.pgsql.txt --no-split=CONNECTION,CONTEXT,AUTH_OK,VERBOSE,LONG,ING > for-grammar/ext.pgsql.re

pnpm run -s regex-builder for-grammar/input/ext.sockets.txt --split=SOCKET_ENOT,SOCKET_ENO,SOCKET_E --no-split=SOCK_,BLOCK,WANT,QUEUE,CTRUNC,TYPE,OOBINLINE,GESTION,ACCEPT,SUPPORT,EMPTY,REMOTE,PERM,STREAM,AGAIN,L2,2BIG,PROGRESS,ACCES,PIPE,LOOP,SIZE,FILE,DIR,IDRM,EXIST,FAULT,START,LONG,RESET,REMCHG,ABORTED,SOL_,COMM,MAX,RNG,IPV,LINK,IPPRO,MEDIUM,NET,INTR,ADDR,DONT,DEBUG,ROFS,EOF --min-word-split 2 > for-grammar/ext.sockets.re

pnpm run -s regex-builder for-grammar/input/ext.sodium.txt --no-split=VERSION,LIMIT,MODERATE,SENSITIVE,MAJOR,KEY,BYTES --split=SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_A > for-grammar/ext.sodium.re

pnpm run -s regex-builder for-grammar/input/ext.curl.txt --no-split=VERSION,LIMIT,MODERATE,SENSITIVE,IGNORED,V4,CURL_,_PRIOR_KNOWLEDGE,PAUSE,301,2_0,SHARE,302,NONE,ACTIVE,PROTO,303,2TLS,MOD,SERVER,NAME,PROTOCOL,MAJOR,AUTH,MATCH,PROXY,SIGNAL,PROGRESS,TARGET,SOCKET,WEIGHT,WAIT,MODE,DONE,ERR,EXIT,CERT,EFFORT,HOST,WORD,NET,CIPHER,FILE,ENABLE,INFO,PATH,TEXT,LIST,SCHEME,SIZE,CODE,LOAD,BEARER,ERROR,SERVERS,TELNET,HTTP,FTP,PORT,KEY,TRANSFER,PRIVATE,PRIMARY,CRLF,LDAP,SCOPE,VERBOSE,SOLVE,IMAP,RANGE,RANDOM,QUOTE,FACE,LOCATION,FUNCTION,SMTP,CLOSED,REJECTED,ALLOWED,REFUSED,AFTER,REFERER,CWD,RECORD,DOWN,RECEIVE,FUNC,DESCRIBE,CONNECT,CONDITION,CONTENT,MISS,EXPIRED > for-grammar/ext.curl.re

# Compact mode:

pnpm run -s regex-builder --balanced 100 for-grammar/input/ext.intl.txt --no-split=VALID,STANDARD,TOKEN,VERSION,OPTION,FILTER,PROHIBITED,ACCESS,RULE,OPERATOR > for-grammar/ext.intl.COMPACT.re

pnpm run -s regex-builder --balanced 100 for-grammar/input/ext.pgsql.txt --no-split=CONNECTION,CONTEXT,AUTH_OK,VERBOSE,LONG,ING > for-grammar/ext.pgsql.COMPACT.re

pnpm run -s regex-builder --balanced 100 for-grammar/input/ext.sockets.txt --split=SOCKET_ENOT,SOCKET_ENO,SOCKET_E --no-split=SOCK_,BLOCK,WANT,QUEUE,CTRUNC,TYPE,OOBINLINE,GESTION,ACCEPT,SUPPORT,EMPTY,REMOTE,PERM,STREAM,AGAIN,L2,2BIG,PROGRESS,ACCES,PIPE,LOOP,SIZE,FILE,DIR,IDRM,EXIST,FAULT,START,LONG,RESET,REMCHG,ABORTED,SOL_,COMM,MAX,RNG,IPV,LINK,IPPRO,MEDIUM,NET,INTR,ADDR,DONT,DEBUG,ROFS,EOF --min-word-split 2 > for-grammar/ext.sockets.COMPACT.re

pnpm run -s regex-builder --balanced 100 for-grammar/input/ext.sodium.txt --no-split=VERSION,LIMIT,MODERATE,SENSITIVE,MAJOR,KEY,BYTES --split=SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_A > for-grammar/ext.sodium.COMPACT.re

pnpm run -s regex-builder --balanced 100 for-grammar/input/ext.curl.txt --no-split=VERSION,LIMIT,MODERATE,SENSITIVE,IGNORED,V4,CURL_,_PRIOR_KNOWLEDGE,PAUSE,301,2_0,SHARE,302,NONE,ACTIVE,PROTO,303,2TLS,MOD,SERVER,NAME,PROTOCOL,MAJOR,AUTH,MATCH,PROXY,SIGNAL,PROGRESS,TARGET,SOCKET,WEIGHT,WAIT,MODE,DONE,ERR,EXIT,CERT,EFFORT,HOST,WORD,NET,CIPHER,FILE,ENABLE,INFO,PATH,TEXT,LIST,SCHEME,SIZE,CODE,LOAD,BEARER,ERROR,SERVERS,TELNET,HTTP,FTP,PORT,KEY,TRANSFER,PRIVATE,PRIMARY,CRLF,LDAP,SCOPE,VERBOSE,SOLVE,IMAP,RANGE,RANDOM,QUOTE,FACE,LOCATION,FUNCTION,SMTP,CLOSED,REJECTED,ALLOWED,REFUSED,AFTER,REFERER,CWD,RECORD,DOWN,RECEIVE,FUNC,DESCRIBE,CONNECT,CONDITION,CONTENT,MISS,EXPIRED > for-grammar/ext.curl.COMPACT.re