SODIUM_(
       BASE64_VARIANT_(
                      ORIGINAL(_NO_PADDING)?
                      |URLSAFE(_NO_PADDING)?
       )
       |CRYPTO_(
               AEAD_(
                    AES256GCM_(A|KEY|NPUB|NSEC)BYTES
                    |CHACHA20POLY1305_(
                                      (A|KEY|NPUB|NSEC)BYTES
                                      |IETF_(A|KEY|NPUB|NSEC)BYTES
                    )
                    |XCHACHA20POLY1305_IETF_(A|KEY|NPUB|NSEC)BYTES
               )
               |AUTH_(BYTES|KEYBYTES)
               |BOX_(KEYPAIR|MAC|NONCE|PUBLICKEY|SEAL|SECRETKEY|SEED)BYTES
               |CORE_RISTRETTO255_(B|HASHB|NONREDUCEDSCALARB|SCALARB)YTES
               |GENERICHASH_(
                            BYTES(_(MAX|MIN))?
                            |KEYBYTES(_(MAX|MIN))?
               )
               |KDF_(
                    BYTES_(MAX|MIN)
                    |CONTEXTBYTES|KEYBYTES
               )
               |KX_(KEYPAIR|PUBLICKEY|SECRETKEY|SEED|SESSIONKEY)BYTES
               |PWHASH_(
                       ALG_(
                           ARGON2I(13|D13)
                           |DEFAULT
                       )
                       |MEMLIMIT_(INTERACTIVE|MODERATE|SENSITIVE)
                       |OPSLIMIT_(INTERACTIVE|MODERATE|SENSITIVE)
                       |SCRYPTSALSA208SHA256_(
                                             MEMLIMIT_(INTERACTIVE|SENSITIVE)
                                             |OPSLIMIT_(INTERACTIVE|SENSITIVE)
                                             |SALTBYTES|STRPREFIX
                       )
                       |SALTBYTES|STRPREFIX
               )
               |SCALARMULT_(
                           RISTRETTO255_(BYTES|SCALARBYTES)
                           |BYTES|SCALARBYTES
               )
               |SECRET(
                      BOX_(KEY|MAC|NONCE)BYTES
                      |STREAM_XCHACHA20POLY1305_(
                                                (A|HEADER|KEY)BYTES
                                                |MESSAGEBYTES_MAX
                                                |TAG_(FINAL|MESSAGE|PUSH|REKEY)
                      )
               )
               |SHORTHASH_(BYTES|KEYBYTES)
               |SIGN_(B|KEYPAIRB|PUBLICKEYB|SECRETKEYB|SEEDB)YTES
               |STREAM_(
                       KEYBYTES|NONCEBYTES
                       |XCHACHA20_(KEYBYTES|NONCEBYTES)
               )
       )
       |LIBRARY_((MAJOR|MINOR)_)?VERSION
)
