POSIX_(
        (F|R|W|X)_OK
        |S_IF(REG|BLK|SOCK|CHR|IFO)
        |SC_(
              ARG_MAX|CHILD_MAX|CLK_TCK
              |NPROCESSORS_(CONF|ONLN)
              |PAGESIZE
        )
        |PC_(
            ALLOC_SIZE_MIN|CHOWN_RESTRICTED|LINK_MAX
            |MAX_(CANON|INPUT)
            |NAME_MAX|NO_TRUNC|PATH_MAX|PIPE_BUF|SYMLINK_MAX
        )
        |RLIMIT_(
                AS|CORE|CPU|DATA|FSIZE|INFINITY|LOCKS|MEMLOCK|MSGQUEUE|NICE|NOFILE|NPROC|RSS
                |RT(PRIO|TIME)
                |SIGPENDING|STACK
        )
)