SODIUM_(
       BASE64_VARIANT_(ORIGINAL|URLSAFE)(_NO_PADDING)?
       |CRYPTO_(
               AEAD_(
                    (AES256GCM|XCHACHA20POLY1305_IETF)_(
                                                       ABYTES
                                                       |(KEY|NPUB|NSEC)BYTES
                    )
                    |CHACHA20POLY1305_(
                                      ABYTES
                                      |IETF_(
                                            ABYTES
                                            |(KEY|NPUB|NSEC)BYTES
                                      )
                                      |(KEY|NPUB|NSEC)BYTES
                    )
               )
               |(AUTH|SHORTHASH)_(KEY)?BYTES
               |BOX_(KEYPAIR|MAC|NONCE|PUBLICKEY|SEAL|SECRETKEY|SEED)BYTES
               |CORE_RISTRETTO255_(
                                  HASH
                                  |(NONREDUCED)?SCALAR
               )?BYTES
               |GENERICHASH_(KEY)?BYTES(_(MAX|MIN))?
               |KDF_(
                    BYTES_(MAX|MIN)
                    |CONTEXTBYTES|KEYBYTES
               )
               |KX_(
                   (PUBLIC|SECRET|SESSION)KEY
                   |KEYPAIR|SEED
               )BYTES
               |PWHASH_(
                       ALG_(
                           ARGON2I(D)?13
                           |DEFAULT
                       )
                       |(MEMLIMIT|OPSLIMIT)_(INTERACTIVE|MODERATE|SENSITIVE)
                       |SCRYPTSALSA208SHA256_(
                                             (MEMLIMIT|OPSLIMIT)_(INTERACTIVE|SENSITIVE)
                                             |SALTBYTES|STRPREFIX
                       )
                       |SALTBYTES|STRPREFIX
               )
               |SCALARMULT_(RISTRETTO255_)?(SCALAR)?BYTES
               |SECRET(
                      BOX_(KEY|MAC|NONCE)BYTES
                      |STREAM_XCHACHA20POLY1305_(
                                                ABYTES|HEADERBYTES|KEYBYTES|MESSAGEBYTES_MAX
                                                |TAG_(FINAL|MESSAGE|PUSH|REKEY)
                      )
               )
               |SIGN_(KEYPAIR|PUBLICKEY|SECRETKEY|SEED)?BYTES
               |STREAM_(
                       KEYBYTES|NONCEBYTES
                       |XCHACHA20_(KEYBYTES|NONCEBYTES)
               )
       )
       |LIBRARY_((MAJOR|MINOR)_)?VERSION
)
