(FORCE_(DEFLATE|GZIP)
|ZLIB_((BUF|DATA|MEM)_ERROR|BLOCK|DEFAULT_STRATEGY|ENCODING_(DEFLATE|GZIP|RAW)|ERRNO|FILTERED
      |FINISH|FIXED|(FULL|NO|PARTIAL|SYNC)_FLUSH|HUFFMAN_ONLY|NEED_DICT|OK|RLE|VERNUM
      |STREAM_(END|ERROR)|VERSION(_ERROR)?))